openapi: 3.0.3
info:
  title: Django DRF Ecommerce
  version: 1.0.0
  description: Your project description
paths:
  /api/category/:
    get:
      operationId: api_category_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
